-- Metadata profile persistence tables.
-- Execute within the metadata database and schema (e.g. via USE DATABASE / USE SCHEMA).

CREATE TABLE IF NOT EXISTS DQ_PROFILE_RUN (
    RUN_ID STRING,
    RUN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    SUMMARY VARIANT,
    PRIMARY KEY (RUN_ID)
);

CREATE TABLE IF NOT EXISTS DQ_PROFILE_COLUMN (
    RUN_ID STRING,
    COLUMN_NAME STRING,
    PROFILE VARIANT,
    PRIMARY KEY (RUN_ID, COLUMN_NAME)
);
