-- Normalize legacy table-level DQ_CHECK rows to use explicit rule codes
-- for freshness and row count anomaly checks, then deduplicate per config.

UPDATE ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_CHECK
SET RULE_CODE = 'TABLE_FRESHNESS_CHECK'
WHERE RULE_CODE IS NULL
  AND RULE_PARAMS:"max_age_minutes" IS NOT NULL;

UPDATE ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_CHECK
SET RULE_CODE = 'TABLE_ROWCOUNT_ANOMALY'
WHERE RULE_CODE IS NULL
  AND RULE_PARAMS:"lookback_days" IS NOT NULL;

DELETE FROM ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_CHECK
WHERE (CONFIG_ID, RULE_CODE, CHECK_ID) IN (
    SELECT CONFIG_ID, RULE_CODE, CHECK_ID
    FROM (
        SELECT CONFIG_ID,
               RULE_CODE,
               CHECK_ID,
               ROW_NUMBER() OVER (
                   PARTITION BY CONFIG_ID, RULE_CODE
                   ORDER BY UPDATED_AT DESC NULLS LAST, CHECK_ID DESC
               ) AS rn
        FROM ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_CHECK
        WHERE RULE_CODE IN ('TABLE_FRESHNESS_CHECK', 'TABLE_ROWCOUNT_ANOMALY')
    )
    WHERE rn > 1
);
