-- Sync DQ_COLUMN_FEATURES with columns expected by DQ_PROFILE_FULL and DQ_APPLY_RULES
-- Safe to run multiple times; uses CREATE TABLE IF NOT EXISTS and additive ALTER TABLE

CREATE TABLE IF NOT EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES (
    PROFILE_RUN_ID NUMBER,
    DATABASE_NAME STRING,
    SCHEMA_NAME STRING,
    TABLE_NAME STRING,
    TABLE_FQN STRING,
    COLUMN_NAME STRING,
    ORDINAL_POSITION NUMBER,
    DATA_TYPE STRING,
    ROW_COUNT NUMBER,
    NULL_COUNT NUMBER,
    NULL_RATIO FLOAT,
    DISTINCT_COUNT NUMBER,
    DISTINCT_RATIO FLOAT,
    MIN_VALUE VARIANT,
    MAX_VALUE VARIANT,
    SAMPLE_PATTERNS VARIANT,
    MIN_LENGTH NUMBER,
    MAX_LENGTH NUMBER,
    AVG_LENGTH FLOAT,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

-- Add any missing columns for older deployments without dropping existing data
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS PROFILE_RUN_ID NUMBER;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS DATABASE_NAME STRING;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS SCHEMA_NAME STRING;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS TABLE_NAME STRING;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS TABLE_FQN STRING;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS COLUMN_NAME STRING;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS ORDINAL_POSITION NUMBER;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS DATA_TYPE STRING;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS ROW_COUNT NUMBER;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS NULL_COUNT NUMBER;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS NULL_RATIO FLOAT;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS DISTINCT_COUNT NUMBER;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS DISTINCT_RATIO FLOAT;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS MIN_VALUE VARIANT;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS MAX_VALUE VARIANT;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS SAMPLE_PATTERNS VARIANT;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS MIN_LENGTH NUMBER;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS MAX_LENGTH NUMBER;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS AVG_LENGTH FLOAT;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_COLUMN_FEATURES ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP;
