-- Extends DQ_RULE_LIBRARY to support DSL/template-based rules without removing legacy columns
-- Safe to run multiple times; uses IF NOT EXISTS and backfills from existing columns where possible.

-- Ensure new metadata columns exist for DSL engine support
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY ADD COLUMN IF NOT EXISTS RULE_CODE STRING;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY ADD COLUMN IF NOT EXISTS SCOPE STRING;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY ADD COLUMN IF NOT EXISTS ENGINE_TYPE STRING;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY ADD COLUMN IF NOT EXISTS EXPRESSION STRING;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY ADD COLUMN IF NOT EXISTS DEFAULT_PARAMS VARIANT;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY ADD COLUMN IF NOT EXISTS ALLOWED_DATA_TYPES VARIANT;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY ADD COLUMN IF NOT EXISTS ALLOWED_CLASSIFICATIONS VARIANT;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY ADD COLUMN IF NOT EXISTS CATEGORY STRING;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY ADD COLUMN IF NOT EXISTS SEVERITY STRING;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY ADD COLUMN IF NOT EXISTS ENABLED BOOLEAN;
ALTER TABLE IF EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY ADD COLUMN IF NOT EXISTS VERSION NUMBER(38,0);

-- Backfill new columns from existing data where available
UPDATE ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY
SET
    RULE_CODE = COALESCE(RULE_CODE, RULE_ID),
    SCOPE = COALESCE(SCOPE, 'COLUMN'),
    ENGINE_TYPE = COALESCE(ENGINE_TYPE, 'TEMPLATE'),
    EXPRESSION = COALESCE(EXPRESSION, EXPRESSION_TEMPLATE),
    DEFAULT_PARAMS = COALESCE(DEFAULT_PARAMS, PARSE_JSON('{}')),
    CATEGORY = COALESCE(CATEGORY, CHECK_TYPE),
    SEVERITY = COALESCE(SEVERITY, DEFAULT_SEVERITY),
    ENABLED = COALESCE(ENABLED, ACTIVE),
    VERSION = COALESCE(VERSION, 1)
WHERE TRUE;
