-- Ensures ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY supports dynamic rule templates

CREATE TABLE IF NOT EXISTS ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY (
    RULE_UID STRING DEFAULT UUID_STRING() NOT NULL,
    RULE_ID VARCHAR NOT NULL,
    CHECK_TYPE VARCHAR,
    EXPRESSION_TEMPLATE VARCHAR,
    PARAM_SCHEMA VARIANT,
    DEFAULT_SEVERITY VARCHAR,
    DESCRIPTION VARCHAR,
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    DATA_TYPE_FAMILY VARCHAR,
    APPLICABILITY_TAGS VARIANT,
    DEFAULT_SUGGEST BOOLEAN DEFAULT TRUE,
    SUGGESTION_PRIORITY NUMBER(38,0),
    CONSTRAINT PK_DQ_RULE_LIBRARY PRIMARY KEY (RULE_UID)
);

ALTER TABLE ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY
    ADD COLUMN IF NOT EXISTS RULE_UID STRING;

ALTER TABLE ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY
    ADD COLUMN IF NOT EXISTS DATA_TYPE_FAMILY VARCHAR;

ALTER TABLE ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY
    ADD COLUMN IF NOT EXISTS APPLICABILITY_TAGS VARIANT;

ALTER TABLE ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY
    ADD COLUMN IF NOT EXISTS DEFAULT_SUGGEST BOOLEAN DEFAULT TRUE;

ALTER TABLE ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY
    ADD COLUMN IF NOT EXISTS SUGGESTION_PRIORITY NUMBER(38,0);

ALTER TABLE ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY
    ALTER COLUMN RULE_UID SET DEFAULT UUID_STRING();

UPDATE ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY
SET RULE_UID = UUID_STRING()
WHERE RULE_UID IS NULL;

ALTER TABLE ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY
    ALTER COLUMN RULE_UID SET NOT NULL;

-- Drop any remaining primary key or unique constraints that include RULE_ID
DECLARE
    constraint_name VARCHAR;
BEGIN
    FOR rec IN (
        SELECT tc.constraint_name
        FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
        WHERE tc.table_catalog = 'ZEUS_ANALYTICS_SIMU'
          AND tc.table_schema = 'DISCOVERY'
          AND tc.table_name = 'DQ_RULE_LIBRARY'
          AND tc.constraint_type IN ('PRIMARY KEY', 'UNIQUE')
          AND EXISTS (
              SELECT 1
              FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu
              WHERE ccu.table_catalog = tc.table_catalog
                AND ccu.table_schema = tc.table_schema
                AND ccu.table_name = tc.table_name
                AND ccu.constraint_name = tc.constraint_name
                AND UPPER(ccu.column_name) = 'RULE_ID'
          )
    ) DO
        EXECUTE IMMEDIATE 'ALTER TABLE ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY DROP CONSTRAINT ' || rec.constraint_name;
    END FOR;
END;

ALTER TABLE ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY
    ADD CONSTRAINT IF NOT EXISTS PK_DQ_RULE_LIBRARY PRIMARY KEY (RULE_UID);

UPDATE ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY
SET
    DATA_TYPE_FAMILY = COALESCE(DATA_TYPE_FAMILY, 'ANY'),
    APPLICABILITY_TAGS = COALESCE(APPLICABILITY_TAGS, PARSE_JSON('[]')),
    DEFAULT_SUGGEST = COALESCE(DEFAULT_SUGGEST, TRUE),
    SUGGESTION_PRIORITY = COALESCE(SUGGESTION_PRIORITY, 50)
WHERE TRUE;

MERGE INTO ZEUS_ANALYTICS_SIMU.DISCOVERY.DQ_RULE_LIBRARY AS target
USING (
    SELECT
        RULE_ID,
        CHECK_TYPE,
        EXPRESSION_TEMPLATE,
        PARSE_JSON(PARAM_SCHEMA_JSON) AS PARAM_SCHEMA,
        DEFAULT_SEVERITY,
        DESCRIPTION,
        ACTIVE
    FROM (
        SELECT
            'NOT_NULL_BASIC' AS RULE_ID,
            'NOT_NULL' AS CHECK_TYPE,
            '({column_expr} IS NOT NULL)' AS EXPRESSION_TEMPLATE,
            '[]' AS PARAM_SCHEMA_JSON,
            'HIGH' AS DEFAULT_SEVERITY,
            'Basic non-null check' AS DESCRIPTION,
            TRUE AS ACTIVE
        UNION ALL SELECT
            'RANGE_NUMERIC',
            'RANGE',
            '({column_expr} BETWEEN {min_value} AND {max_value})',
            '["min_value","max_value"]',
            'MEDIUM',
            'Numeric allowed range',
            TRUE
        UNION ALL SELECT
            'ENUM_SMALL_CARDINALITY',
            'ENUM',
            '({column_expr} IN ({allowed_values}))',
            '["allowed_values"]',
            'MEDIUM',
            'Enumeration check for low-cardinality columns',
            TRUE
        UNION ALL SELECT
            'NOT_FUTURE_DATE',
            'DATE_CHECK',
            '({column_expr} <= CURRENT_DATE())',
            '[]',
            'HIGH',
            'Values cannot be in the future',
            TRUE
        UNION ALL SELECT
            'PATTERN_BASIC',
            'PATTERN',
            '({column_expr} REGEXP {pattern})',
            '["pattern"]',
            'LOW',
            'Regex pattern match',
            TRUE
    )
) AS source
ON target.RULE_ID = source.RULE_ID
WHEN MATCHED THEN UPDATE SET
    CHECK_TYPE = source.CHECK_TYPE,
    EXPRESSION_TEMPLATE = source.EXPRESSION_TEMPLATE,
    PARAM_SCHEMA = source.PARAM_SCHEMA,
    DEFAULT_SEVERITY = source.DEFAULT_SEVERITY,
    DESCRIPTION = source.DESCRIPTION,
    ACTIVE = source.ACTIVE,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    RULE_ID,
    CHECK_TYPE,
    EXPRESSION_TEMPLATE,
    PARAM_SCHEMA,
    DEFAULT_SEVERITY,
    DESCRIPTION,
    ACTIVE
) VALUES (
    source.RULE_ID,
    source.CHECK_TYPE,
    source.EXPRESSION_TEMPLATE,
    source.PARAM_SCHEMA,
    source.DEFAULT_SEVERITY,
    source.DESCRIPTION,
    source.ACTIVE
);
