name: SQLFluff Lint

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install sqlfluff
        run: pip install sqlfluff
      - name: Lint SQL files
        run: sqlfluff lint sql
